# Generated by Django 3.1.12 on 2025-07-23 17:03

import cm_db.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CM_Card',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('barcode', models.CharField(default='NoID', max_length=20)),
                ('ECOND', models.CharField(default='NoEconD', max_length=20)),
                ('ECONT', models.CharField(default='NoEconT', max_length=20)),
                ('summary', djongo.models.fields.EmbeddedField(model_container=cm_db.models.Summary)),
                ('test_outcomes', djongo.models.fields.ArrayField(model_container=cm_db.models.Test_Outcome, null=True)),
                ('comments', models.CharField(max_length=1000, null=True)),
                ('locations', djongo.models.fields.ArrayField(default=[], model_container=cm_db.models.Location)),
            ],
        ),
        migrations.CreateModel(
            name='Overall_Summary',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('test_types', djongo.models.fields.ArrayField(default=list, model_container=cm_db.models.Test_Type, model_form_class=cm_db.models.Test_Type_Form)),
                ('passedcards', models.IntegerField(default=0)),
                ('failedcards', models.IntegerField(default=0)),
                ('totalcards', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('test_name', models.CharField(default='NoTest', max_length=20)),
                ('barcode', models.CharField(default='NoID', max_length=20)),
                ('tester', models.CharField(default='unknown', max_length=20)),
                ('date_run', models.CharField(default='null', max_length=20)),
                ('outcome', models.CharField(default='null', max_length=10)),
                ('valid', models.BooleanField(default=True)),
                ('overwrite_pass', models.BooleanField(default=False)),
                ('eRX_errcounts', models.BinaryField()),
                ('eTX_delays', models.BinaryField()),
                ('eTX_bitcounts', models.BinaryField()),
                ('eTX_errcounts', models.BinaryField()),
                ('longrepr', models.TextField(max_length=2000, null=True)),
                ('stdout', models.TextField(max_length=2000, null=True)),
                ('crashpath', models.TextField(max_length=2000, null=True)),
                ('crashmsg', models.TextField(max_length=2000, null=True)),
                ('filename', models.CharField(max_length=50, unique=True)),
                ('branch', models.CharField(default='NO_BRANCH', max_length=20)),
                ('commit_hash', models.CharField(default='NO_COMMIT_HASH', max_length=30)),
                ('remote_url', models.CharField(default='NO_URL', max_length=50)),
                ('status', models.CharField(default='NO_STATUS', max_length=50)),
                ('firmware_name', models.CharField(default='NO_FIRMWARE_NAME', max_length=30)),
                ('firmware_git_desc', models.CharField(default='NO_GIT_DESC', max_length=20)),
                ('ECON_TYPE', models.CharField(default='Unknown', max_length=10)),
                ('comments', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'ordering': ('date_run',),
            },
        ),
        migrations.CreateModel(
            name='Test_Details',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('required', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('affiliation', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TestStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('calibration_date', models.DateField()),
            ],
        ),
    ]
