# Generated by Django 3.1.12 on 2025-07-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('metrics', models.JSONField()),
                ('result', models.CharField(max_length=10)),
                ('filename', models.CharField(max_length=200, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
