# Generated by Django 3.1.12 on 2025-07-15 15:28

from django.db import migrations, models
import djongo.models.fields
import logviewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('logviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overall_Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_types', djongo.models.fields.ArrayField(model_container=logviewer.models.Test_Type, model_form_class=logviewer.models.Test_Type_Form)),
                ('passedcards', models.IntegerField()),
                ('failedcards', models.IntegerField()),
                ('totalcards', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(default='NoTest', max_length=20)),
                ('barcode', models.CharField(default='NoID', max_length=20)),
                ('tester', models.CharField(default='unknown', max_length=20)),
                ('date_run', models.CharField(default='null', max_length=20)),
                ('outcome', models.CharField(default='null', max_length=10)),
                ('valid', models.BooleanField(default=True)),
                ('overwrite_pass', models.BooleanField(default=False)),
                ('eRX_errcounts', models.BinaryField()),
                ('eTX_delays', models.BinaryField()),
                ('eTX_bitcounts', models.BinaryField()),
                ('eTX_errcounts', models.BinaryField()),
                ('longrepr', models.TextField(max_length=2000, null=True)),
                ('stdout', models.TextField(max_length=2000, null=True)),
                ('crashpath', models.TextField(max_length=2000, null=True)),
                ('crashmsg', models.TextField(max_length=2000, null=True)),
                ('filename', models.CharField(max_length=50, unique=True)),
                ('branch', models.CharField(default='NO_BRANCH', max_length=20)),
                ('commit_hash', models.CharField(default='NO_COMMIT_HASH', max_length=30)),
                ('remote_url', models.CharField(default='NO_URL', max_length=50)),
                ('status', models.CharField(default='NO_STATUS', max_length=50)),
                ('firmware_name', models.CharField(default='NO_FIRMWARE_NAME', max_length=30)),
                ('firmware_git_desc', models.CharField(default='NO_GIT_DESC', max_length=20)),
                ('ECON_TYPE', models.CharField(default='Unknown', max_length=10)),
                ('comments', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'ordering': ('date_run',),
            },
        ),
    ]
